#!/bin/sh
set -uxe

[ -d ~/dotfiles ] || git clone https://github.com/pixelcmtd/dotfiles.git ~/dotfiles
cd ~/dotfiles

for x in $@ ; do
        if [ -d $x ] ; then
                cd $x
                ./run
                cd ..
        else
                ./$x
        fi
done
