#!/bin/sh
set -uxe

for x in "$@" ; do
        [ -e "$x" ]
        if [ -d "$x" ] ; then
                [ ! -f "$x/run" ] || ( cd "$x" && ./run )
                stow -vv "$x"
        fi
        [ ! -f "$x" ] || "./$x"
done
