disable = ["vim", "node"]
cleanup = true

[git]
pull_predefined = false
repos = [
    "~/.doom.d",
    "~/.emacs.d",
    "~/Carp",
    "~/FreeBSD",
    "~/c++std",
    "~/dotfiles",
    "~/linux",
    "~/llvm",
]
