disable = ["cargo", "vim", "node", "pnpm"]
cleanup = true

[git]
max_concurrency = 10
pull_predefined = false
repos = [
    "~/src/*",
    "~/src/*/*",
]

[commands]
"dotfiles" = "cd ~/src/pixelcmtd/dotfiles/base && ./run"
"tldrgal" = "tldrgal update"
