tap "1password/tap"

brew "dockutil"
brew "ios-deploy"
brew "molten-vk"
brew "telnet"
brew "xcodegen"

cask "1password"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "aldente"
cask "android-studio"
cask "arduino-ide"
cask "audacity"
cask "balenaetcher"
cask "blackhole-2ch"
cask "blender"
cask "burp-suite"
cask "discord"
cask "docker-desktop"
cask "easyeda"
cask "eclipse-java"
cask "elgato-control-center"
cask "ferdium"
cask "focusrite-control-2"
cask "freecad"
cask "gimp"
cask "gpg-suite"
cask "helium-browser"
cask "iina"
cask "ilok-license-manager"
cask "inkscape"
cask "kicad"
cask "ltspice"
cask "macfuse"
cask "macs-fan-control"
cask "mactex"
cask "monitorcontrol"
cask "mumble"
cask "musescore"
cask "native-access"
cask "obs"
cask "ollama-app"
cask "openscad@snapshot"
cask "parallels@20"
cask "prismlauncher"
cask "raspberry-pi-imager"
cask "softube-central"
cask "spotify"
cask "steam"
cask "surge-synthesizer"
cask "surge-xt"
cask "temurin"
cask "thunderbird"
cask "tor-browser"
cask "vivid-app"
cask "vlc"
cask "vscodium"
cask "wireshark-app"
cask "xquartz"

mas "WeTransfer", id: 1114922065
mas "GeoGebra CAS Calculator", id: 1489962804
mas "Dark Reader for Safari", id: 1438243180
mas "ICE Buddy", id: 1595947689
mas "iStatistica Pro", id: 1447778660
mas "Wayback Machine", id: 1472432422
mas "Refined GitHub", id: 1519867270
mas "Hush", id: 1544743900
mas "Color Picker", id: 1545870783
mas "1Password for Safari", id: 1569813296
mas "Magnet", id: 441258766
mas "Microsoft OneNote", id: 784801555
mas "TickTick", id: 966085870
