#!/bin/zsh
source .env
set -ue

xcode-select -p >/dev/null 2>/dev/null || {
        xcode-select --install
        read -r "?A window that lets you install XCode CLI tools should have opened.
If you've closed it, run \`xcode-select --install\` to reopen it.
Please install the XCode CLI tools and then press enter."
}

[ "$(arch)" != arm64 ] || pgrep -q oahd || {
        read -r '?Detected an ARM CPU, please press enter to agree to the Rosetta 2 license.
To disagree, press ctrl-c.'
        sudo softwareupdate --install-rosetta --agree-to-license
}

set -x

osascript -e 'tell application "System Preferences" to quit'

sudo systemsetup -setcomputersleep Never
sudo systemsetup -setdisplaysleep 10
sudo systemsetup -setusingnetworktime On
sudo systemsetup -setallowpowerbuttontosleepcomputer On
sudo systemsetup -setremotelogin On

sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "Property of chrissx Media. Please message chrissx.lost+found@chrissx.de"

# most defaults are well documented at:
# https://github.com/kevinSuttle/macOS-Defaults/blob/master/.macos
# https://mynixos.com/nix-darwin/options/system.defaults.NSGlobalDomain
# https://github.com/rockyluke/macos-tips

defaults write -g AppleICUNumberSymbols -dict 0 "." 1 " " 10 "." 17 " "
defaults write -g AppleLanguages -array en-US de-DE
defaults write -g AppleLocale -string en_US@rg=dezzzz
defaults write -g AppleMeasurementUnits -string Centimeters
defaults write -g AppleMetricUnits -bool true
defaults write -g AppleTemperatureUnit -string Celsius

defaults write -g ApplePressAndHoldEnabled -bool false
defaults write -g AppleReduceDesktopTinting -bool true
defaults write -g AppleShowAllExtensions -bool true
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 2
defaults write -g NSAutomaticCapitalizationEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticInlinePredictionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSPreferredWebServices -dict NSWebServicesProviderWebSearch '{ NSDefaultDisplayName = DuckDuckGo; NSProviderIdentifier = "com.duckduckgo"; }'
defaults write -g com.apple.mouse.linear -bool true
defaults write -g com.apple.swipescrolldirection -bool false

defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
defaults write com.apple.finder _FXSortFoldersFirst -bool true
defaults write com.apple.finder AppleShowAllFiles -bool true
defaults write com.apple.finder DisableAllAnimations -bool true
defaults write com.apple.finder FXConnectToLastURL -string "smb://rotmain.chrissx.de"
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file://$HOME"
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder ShowStatusBar -bool true

defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -float 0
defaults write com.apple.dock launchanim -bool false

defaults write com.apple.Safari SearchProviderShortName -string DuckDuckGo
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari WebKitPreferences.developerExtrasEnabled -bool true

defaults write com.apple.Music losslessEnabled -bool true
defaults write com.apple.Music preferredDownloadAudioQuality -int 15 # up to 48kHz 24bit
defaults write com.apple.Music preferredStreamPlaybackAudioQuality -int 15
defaults write com.apple.Music downloadDolbyAtmos -bool true
defaults write com.apple.Music userMaxConcurrentDownloads -int 3
defaults write com.apple.Music userWantsPlaybackNotifications -bool false
defaults write com.apple.Music dontWarnAboutRequiringExternalHardware -bool true
defaults write com.apple.Music automaticallyDownloadArtwork -bool true
defaults write com.apple.Music encoderName -string "Lossless Encoder"

chflags nohidden "$HOME/Library"

brew bundle install -v

pip3 install --user pyyaml==5.3.1 gen-compose
mkdir -p ~/Library/KeyBindings
gen-compose Compose.yaml > ~/Library/KeyBindings/DefaultKeyBinding.dict

grep pinentry ~/.gnupg/gpg-agent.conf || \
        echo pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac >> ~/.gnupg/gpg-agent.conf

cd .. && ./run kilobase

dockutil --remove all --no-restart
set +x
for app in \
    "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app" \
    "/Applications/Helium.app" \
    "/Applications/Brave Browser.app" \
    "/System/Applications/App Store.app" \
    "/System/Applications/Photos.app" \
    "/Applications/iTerm.app" \
    "/Applications/Ghostty.app" \
    "/System/Applications/System Settings.app" \
    "/Applications/VSCodium.app" \
    "/System/Applications/FaceTime.app" \
    "/Applications/Numbers.app" \
    "/Applications/Keynote.app" \
    "/System/Applications/Notes.app" \
    "/Applications/Microsoft OneNote.app" \
    "/Applications/TickTick.app" \
    "/System/Applications/Music.app" \
    "/Applications/Thunderbird.app" \
    "/System/Applications/Mail.app" \
    "/Applications/FL Studio 2024.app" \
    "/Applications/DaVinci Resolve/DaVinci Resolve.app" \
    "/Applications/LosslessCut.app" \
    "/Applications/OBS.app" \
    "/Applications/Affinity Designer 2.app" \
    "/System/Applications/Messages.app" \
    "/Applications/Ferdium.app" \
    "/Applications/Signal.app" \
    "/Applications/EasyEDA-Pro.app" \
    "/Applications/Ollama.app" \
    "/Applications/T3 Code (Alpha).app"
do
    if [ -d "$app" ] ; then
        dockutil --add "$app" --no-restart
    else
        echo "APP MISSING: $app"
    fi
done
set -x
killall Dock
