#!/bin/zsh
source .env
set -ue

xcode-select -p >/dev/null 2>/dev/null || {
        xcode-select --install
        read -r "?A window that lets you install XCode CLI tools should have opened.
If you've closed it, run \`xcode-select --install\` to reopen it.
Please install the XCode CLI tools and then press enter."
}

[ "$(arch)" != arm64 ] || pgrep -q oahd || {
        read -r '?Detected an ARM CPU, please press enter to agree to the Rosetta 2 license.
To disagree, press ctrl-c.'
        sudo softwareupdate --install-rosetta --agree-to-license
}

set -x

osascript -e 'tell application "System Preferences" to quit'

sudo systemsetup -setcomputersleep Never
sudo systemsetup -setdisplaysleep 10
sudo systemsetup -setusingnetworktime On
sudo systemsetup -setallowpowerbuttontosleepcomputer On
sudo systemsetup -setremotelogin On

brew bundle install -v

pip3 install --user pyyaml==5.3.1 gen-compose
mkdir -p ~/Library/KeyBindings
gen-compose Compose.yaml > ~/Library/KeyBindings/DefaultKeyBinding.dict

defaults write .GlobalPreferences AppleICUNumberSymbols '{ 0 = "."; 1 = " "; 10 = "."; 17 = " "; }'
defaults write .GlobalPreferences AppleLanguages '("en-US", "de-DE")'
defaults write .GlobalPreferences AppleLocale en_DE
defaults write .GlobalPreferences AppleMeasurementUnits Centimeters
defaults write .GlobalPreferences AppleMetricUnits 1
defaults write .GlobalPreferences AppleReduceDesktopTinting 1
defaults write .GlobalPreferences AppleShowAllExtensions 1
defaults write .GlobalPreferences AppleTemperatureUnit Celsius
defaults write .GlobalPreferences com.apple.sound.beep.flash 0
defaults write .GlobalPreferences NSPreferredWebServices '{ NSWebServicesProviderWebSearch = { NSDefaultDisplayName = DuckDuckGo; NSProviderIdentifier = "com.duckduckgo"; }; }'
defaults write .GlobalPreferences com.apple.mouse.linear 1

defaults write com.apple.Safari SearchProviderShortName DuckDuckGo
defaults write com.apple.Safari AutoOpenSafeDownloads 0
defaults write com.apple.Safari ShowFullURLInSmartSearchField 1
defaults write com.apple.Safari IncludeDevelopMenu 1
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey 1
defaults write com.apple.Safari WebKitPreferences.developerExtrasEnabled 1

defaults write com.apple.Music losslessEnabled 1
defaults write com.apple.Music downloadDolbyAtmos 1
defaults write com.apple.Music userWantsPlaybackNotifications 0
defaults write com.apple.Music dontWarnAboutRequiringExternalHardware 1
defaults write com.apple.Music encoderName "Lossless Encoder"

grep pinentry ~/.gnupg/gpg-agent.conf || \
        echo pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac >> ~/.gnupg/gpg-agent.conf

cd .. && ./run base
