#!/bin/zsh
set -ue

xcode-select -p >/dev/null 2>/dev/null || {
        xcode-select --install
        read -rp "A window that lets you install XCode CLI tools should have opened.
If you've closed it, run \`xcode-select --install\` to reopen it.
Please install the XCode CLI tools and then press enter."
}

[ "$(arch)" != arm64 ] || pgrep -q oahd || {
        read -rp 'Detected an ARM CPU, please press enter to agree to the Rosetta 2 license.
To disagree, press ctrl-c.'
        sudo softwareupdate --install-rosetta --agree-to-license
}

set -x

sudo systemsetup -setcomputersleep Never
sudo systemsetup -setdisplaysleep 10
sudo systemsetup -setusingnetworktime On
sudo systemsetup -setallowpowerbuttontosleepcomputer On
sudo systemsetup -setremotelogin On

source .env

[[ -d /opt/homebrew && "$(arch)" = arm64 ]] || \
        [[ -d /usr/local/bin/brew && "$(arch)" = x86_64 ]] || \
        curl -L https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
brew analytics off

brew bundle install
rustup-init --default-toolchain stable --profile default -vy
xe -vf packages.pip3 pip3 install --user

./compile_compose.sh
defaults write .GlobalPreferences AppleICUNumberSymbols '{ 0 = "."; 1 = " "; 10 = "."; 17 = " "; }'
defaults write .GlobalPreferences AppleLanguages '("en-US", "de-DE")'
defaults write .GlobalPreferences AppleLocale en_DE
defaults write .GlobalPreferences AppleMeasurementUnits Centimeters
defaults write .GlobalPreferences AppleMetricUnits 1
defaults write .GlobalPreferences AppleReduceDesktopTinting 1
defaults write .GlobalPreferences AppleShowAllExtensions 1
defaults write .GlobalPreferences AppleTemperatureUnit Celsius
defaults write .GlobalPreferences com.apple.sound.beep.flash 0
defaults write .GlobalPreferences NSPreferredWebServices '{ NSWebServicesProviderWebSearch = { NSDefaultDisplayName = DuckDuckGo; NSProviderIdentifier = "com.duckduckgo"; }; }'

defaults write com.apple.Safari SearchProviderShortName DuckDuckGo
defaults write com.apple.Safari AutoOpenSafeDownloads 0
defaults write com.apple.Safari ShowFullURLInSmartSearchField 1
defaults write com.apple.Safari IncludeDevelopMenu 1
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey 1
defaults write com.apple.Safari WebKitPreferences.developerExtrasEnabled 1

defaults write com.apple.Music losslessEnabled 1
defaults write com.apple.Music downloadDolbyAtmos 1
defaults write com.apple.Music userWantsPlaybackNotifications 0
defaults write com.apple.Music dontWarnAboutRequiringExternalHardware 1
defaults write com.apple.Music encoderName "Lossless Encoder"

echo pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac >> ~/.gnupg/gpg-agent.conf

cd .. && ./run base
