#!/bin/sh
set -uxe

mkdir -p ~/.bin ~/.local/bin

sudo pacman -Syu yay
yay -S `cat packages`
go install golang.org/x/tools/cmd/goimports@latest

sudo cp -f rc.local /etc/rc.d/rc.local
sudo cp -f fancontrol /etc/fancontrol
sudo systemctl enable --now fancontrol
sudo systemctl enable --now dropbear

cd ..
./run vim zsh editorconfig
